"""Data container tracking system-wide runtime state change events."""
from dataclasses import dataclass
from multimodal_notify.core.types import SystemState
from multimodal_notify.core.events.base_event import BaseEvent

@dataclass(frozen=True)
class StateEvent(BaseEvent):
    """Represents a system-wide state change event generated by workers."""
    state: SystemState
    worker_name: str
    message: str
